import { firestore } from "../../Firebase/FirebaseConfig";
const members = [
  {
    Timestamp: "8/20/2021 0:03:17",
    email: "121910310017@gitam.in",
    regId: 121910310017,
    yearOfStudy: 3,
    branch: "CSE",
    name: "Jyothi Prakash",
    personalMail: "jyothiprakashpatnaik@gmail.com",
    role: "Web Developer",
    linkedIn: "https://www.linkedin.com/in/jyothiprakash-patnaikuni-5b070a1aa/",
    instagram: "https://www.instagram.com/people_call.me_jp._/",
    github: "https://github.com/jyothiprakashpanaik",
    twitter: "https://twitter.com/JyothiprakashP7",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1ApaeBeIQui3aba2PshmVz_vfV59PkqYH",
  },
  {
    Timestamp: "8/20/2021 1:42:19",
    email: "121910305006@gitam.in",
    regId: 121910305006,
    yearOfStudy: 3,
    branch: "CSE",
    name: "M. Abdul Habeeb",
    personalMail: "habeeb.1mohd@gmail.com",
    role: "Competitive Programming",
    linkedIn: "https://www.linkedin.com/in/habeeb-mohammad/",
    instagram: "https://www.instagram.com/habeeb.1mohd/",
    github: "https://github.com/habsion",
    twitter: "https://twitter.com/habeeb_1mohd",
    otherLinks: "https://www.hackerrank.com/dashboard",
    picture:
      "https://drive.google.com/open?id=1215uPxEdcUhjDkAGOvAGsOzhv-7LFlP3",
  },
  {
    Timestamp: "8/20/2021 9:50:13",
    email: "121910317008@gitam.in",
    regId: 121910317008,
    yearOfStudy: "3",
    branch: "CSE",
    name: "Abhishek Srinivasan",
    personalMail: "abhisheksrinivasan5@gmail.com",
    role: "PR & Outreach",
    linkedIn: "https://www.linkedin.com/in/abhshkk/",
    instagram: "https://instagram.com/abhshkkk",
    github: "https://github.com/iamabhshk",
    twitter: "https://twitter.com/abhshkkkk?s=09",
    otherLinks: "Portfolio: https://github.com/iamabhshk",
    picture:
      "https://drive.google.com/open?id=120UrYp0IsXCcgyv8-aGHK6IOQtebX-R0",
  },
  {
    Timestamp: "8/20/2021 10:24:43",
    email: "121913801005@gitam.in",
    regId: 121913801005,
    yearOfStudy: "3",
    branch: "bcom hons acca",
    name: "Hrishita Roy",
    personalMail: "hrishita299@gmail.com",
    role: "public relations",
    linkedIn: "dont have",
    instagram: "hrishu26",
    github: "",
    twitter: "Hrishita2604",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1euISIqQud1AXzdnA1oHiDh4-7FLLqdYF",
  },
  {
    Timestamp: "8/20/2021 10:35:57",
    email: "121910201026@gitam.in",
    regId: 121910201026,
    yearOfStudy: "3",
    branch: "Civil",
    name: "K Uday Kiran",
    personalMail: "kiranuday1026@gmail.com",
    role: "UI/UX Designer",
    linkedIn: "www.linkedin.com/in/uday-kiran-karanam-4791851b5",
    instagram:
      "https://www.instagram.com/invites/contact/?i=dlgmfsjmasvm&utm_content=1s90eyv",
    github: "",
    twitter: "https://twitter.com/UdayKiranKaran1?s=08",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=15lCdnYu53eQQ3nibR44D2xy3LhGR4nQ7",
  },
  {
    Timestamp: "8/23/2021 11:01:45",
    email: "121910308003@gitam.in",
    regId: 121910308003,
    yearOfStudy: 3,
    branch: "CSE",
    name: "Guru Charan",
    personalMail: "guruc134@gmail.com",
    role: "GDSC Lead",
    linkedIn: "https://www.linkedin.com/in/guru-charan-kakaraparty-7103561a1/",
    instagram: "https://www.instagram.com/gurucharan13/",
    github: "https://github.com/guruc-134",
    twitter: "",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1UwMQB7suoPzkmY3nGH2INLBoLPnNh5uI",
  },
  {
    Timestamp: "8/23/2021 11:03:16",
    email: "121910313004@gitam.in",
    regId: 121910313004,
    yearOfStudy: 3,
    branch: "CSE",
    name: "Janapareddy Raghuramjee",
    personalMail: "ramjeeraghu@gmail.com",
    role: "CP",
    linkedIn: "linkedin.com/in/raghu-ramjee-b6363718a/",
    instagram: "https://www.instagram.com/raghuramjeee/",
    github: "https://github.com/raghuramjee7",
    twitter: "https://twitter.com/raghuramjeee",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1o7zsNKOlN5yJD0kT6ri4xjMqGPNjBGzL",
  },
  {
    Timestamp: "8/23/2021 11:04:19",
    email: "121910317017@gitam.in",
    regId: 1219103170117,
    yearOfStudy: 3,
    branch: "CSE",
    name: "Prithviraj Saha",
    personalMail: "prithvirajsaha1000@gmail.com",
    role: "Content Dev",
    linkedIn: "https://www.linkedin.com/in/prithviraj-saha-5395921b2",
    instagram: "https://www.instagram.com/prithvi078/",
    github: "https://github.com/121910317017-Prithviraj",
    twitter: "https://twitter.com/prithvi078",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=19y4XbhtcEiVqLoOIADwMXGOiOvvufmhH",
  },
  {
    Timestamp: "8/23/2021 11:06:38",
    email: "121910316053@gitam.in",
    regId: 121910316053,
    yearOfStudy: "3rd year",
    branch: "CSE",
    name: "B Sivasai",
    personalMail: "sivasai.bavanasi@gmail.com",
    role: "App dev",
    linkedIn: "https://www.linkedin.com/in/bhavanasi-sivasai-b759101a0",
    instagram: "",
    github: "",
    twitter: "",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1E_7i_DpcalvFQMJ_vCRfUGPMkjTbdZGB",
  },
  {
    Timestamp: "8/23/2021 11:08:19",
    email: "121910312015@gitam.in",
    regId: 121910312015,
    yearOfStudy: "3rd yr",
    branch: "CSE",
    name: "A.Leela Prasanti",
    personalMail: "leelaprasanti5101@gmail.com",
    role: "Content",
    linkedIn: "linkedin.com/in/leela-prasanti-8871b9205",
    instagram: "leelaanand501",
    github: "121910312015leela",
    twitter: "NIL",
    otherLinks: "Medium: \thttps://medium.com/@leelaprasanti5101",
    picture:
      "https://drive.google.com/open?id=1wCCqIaxKyW76Lf2-5eY6XN6CZ-6U-G1y",
  },
  {
    Timestamp: "8/23/2021 11:08:40",
    email: "121910302007@gitam.in",
    regId: 121910302007,
    yearOfStudy: 3,
    branch: "CSE",
    name: "Divyansh Gupta",
    personalMail: "divyanshgupta2108@gmail.com",
    role: "OPERATIONS LEAD",
    linkedIn: "https://www.linkedin.com/in/divyansh-gupta-935637197",
    instagram: "divyaaaansshh",
    github: "https://github.com/divyansh-gupta-0210",
    twitter: "Divyanshgupta26",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1R0SpyxtdYzmkl8BJjlpx8DeYN80XIvhf",
  },
  {
    Timestamp: "8/23/2021 11:09:45",
    email: "121910318003@gitam.in",
    regId: 121910318003,
    yearOfStudy: 3,
    branch: "CSE",
    name: "B. Sameer Sowrab",
    personalMail: "sameersowrab9949@gmail.com",
    role: "AI/ML/DS",
    linkedIn: "www.linkedin.com/in/sameer-sowrab",
    instagram: "sameersowrab",
    github: "https://github.com/sowrab9949",
    twitter: "",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1GzcC09lR2l4mTtNpuzXfeFinzt7O-jsm",
  },
  {
    Timestamp: "8/23/2021 11:10:16",
    email: "121910302059@gitam.in",
    regId: "121910302059@gitam.in",
    yearOfStudy: "3rd",
    branch: "Cse",
    name: "kushal ippili",
    personalMail: "ippilikushal@gmail.com",
    role: "CP LEAD",
    linkedIn: "https://www.linkedin.com/in/kushal-ippili-abb810190/",
    instagram: "https://www.instagram.com/kushal_ippili/",
    github: "https://github.com/kushal13112001",
    twitter: "https://twitter.com/ippilikushal",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1L-ZKyxJ1NoqVPWq13Zq52g7YMYlGbNlE",
  },
  {
    Timestamp: "8/23/2021 11:12:17",
    email: "121910308040@gitam.in",
    regId: 121910308040,
    yearOfStudy: "3rd Year",
    branch: "CSE",
    name: "Sanjana Rayavarapu",
    personalMail: "rayavarapusanjana@gmail.com",
    role: "Content Writing",
    linkedIn: "https://www.linkedin.com/in/sanjana~rayavarapu/",
    instagram: "",
    github: "https://github.com/SanjanaRayavarapu",
    twitter: "",
    otherLinks: "https://sanjanarayavarapu.hashnode.dev/",
    picture:
      "https://drive.google.com/open?id=199qHn-45Wy5x7FueQwgQpPu2g7uFQsm0",
  },
  {
    Timestamp: "8/23/2021 11:32:02",
    email: "121910317028@gitam.in",
    regId: 121910317028,
    yearOfStudy: 3,
    branch: "CSE",
    name: "D Dheeraj Chowdary",
    personalMail: "dheerudoppalapudi@gmail.com",
    role: "Web-development",
    linkedIn: "https://www.linkedin.com/in/d-dheeraj-chowdary",
    instagram: "https://www.instagram.com/doppalapudidheeraj/",
    github: "https://github.com/Dheerajdoppalapudi",
    twitter: "",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1uYit8LZCb2Jh6uUdUPTFuG9v0ZLTg5mV",
  },
  {
    Timestamp: "8/23/2021 11:33:59",
    email: "121910303051@gitam.in",
    regId: 121910303051,
    yearOfStudy: "3rd year",
    branch: "CSE",
    name: "V SUNIL TAGORE",
    personalMail: "vsuniltagore858@gmail.com",
    role: "AI/ML(lead)",
    linkedIn: "https://www.linkedin.com/in/sunil-tagore-veluturi-366b8917b/",
    instagram: "https://www.instagram.com/vsuniltagore/",
    github: "https://github.com/Sunil-tagore",
    twitter: "",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=1P3uymB89nICFJJWrf-VBLteguGmIHIko",
  },
  {
    Timestamp: "8/23/2021 11:37:53",
    email: "121910403019@gitam.in",
    regId: 121910403019,
    yearOfStudy: "3rd",
    branch: "ECE",
    name: "Ashima Rai",
    personalMail: "ashimarai2001@gmail.com",
    role: "PR team",
    linkedIn: "HTTPS://WWW.LINKEDIN.COM/I N/ ASHIM A-R AI-14651663",
    instagram: "@_ashimarai_       @artshiii",
    github: "",
    twitter: "",
    otherLinks: "",
    picture:
      "https://drive.google.com/open?id=10V94Agu7joDWYP7gcg2pV1YYf2aKVdeS",
  },
  {
    Timestamp: "8/23/2021 12:02:43",
    email: "121910302022@gitam.in",
    regId: 121910302022,
    yearOfStudy: 3,
    branch: "CSE",
    name: "Krishna Chaitanya",
    personalMail: "krishna.chaitanya.kanna9@gmail.com",
    role: "WEB DEV",
    linkedIn: "https://www.linkedin.com/in/krishna-chaitanya-78b154199",
    instagram: "https://www.instagram.com/xrishnachaitanya/",
    github:
      "https://github.com/CrishnaChaitanyahttps://www.linkedin.com/in/krishna-chaitanya-78b154199",
    twitter: "",
    otherLinks:
      "https://crishnachaitanya.github.io/React_portfolio_incomplete/",
    picture:
      "https://drive.google.com/open?id=1Xc-QWfaXZG9yQoc5DE8XddKYiy1E2ZtY",
  },
  {
    Timestamp: "8/23/2021 12:18:26",
    email: "121910315006@gitam.in",
    regId: 121910315006,
    yearOfStudy: "3/4",
    branch: "CSE",
    name: "Samuel Vasamsetti",
    personalMail: "samuelvasamsetti@gmail.com",
    role: "App Development",
    linkedIn: "https://www.linkedin.com/in/samuelvasamsetti/",
    instagram: "https://www.instagram.com/prosamva/",
    github: "https://github.com/SamuelVasamsetti",
    twitter: "https://twitter.com/Prosamva",
    otherLinks: "Facebook: https://www.facebook.com/SamuelVasamsetti",
    picture:
      "https://drive.google.com/open?id=1zVw-qD1B26vL8ZV6Fpiw__-y9w3Yo5Xu",
  },
];
const addMembersFun = () => {
  members.map((item) => {
    console.log("adding", item.name);
    firestore.collection("CoreTeam/memberlist/members").add(item);
  });
};

addMembersFun();

export default addMembersFun;
